dist: trusty
sudo: false


language: python


branches:
  only:
    - master


#
# Test test matrix is spelled out explicitly here.
#
# For each supported version of Python, we will test with:
#
#  * The first minor version of Twisted for each major version that supports
#    the tested version of Python, covering two years of releases.
#
#  * The current release of Twisted.
#
#  * Twisted trunk, at the time of the build.
#    This is allowed to fail, as a failure in only this case indicates a likely
#    compatibility bug in Twisted trunk.
#
matrix:
  include:
    # PyPy (Python 2.7)
    - env: TOXENV=trial-pypy-tw155     PYPY_VERSION=5.7.1
    - env: TOXENV=trial-pypy-tw160     PYPY_VERSION=5.7.1
    - env: TOXENV=trial-pypy-twcurrent PYPY_VERSION=5.7.1
    - env: TOXENV=trial-pypy-twtrunk   PYPY_VERSION=5.7.1

    - python: 2.7
      env: TOXENV=trial-py27-tw155
    - python: 2.7
      env: TOXENV=trial-py27-tw160
    - python: 2.7
      env: TOXENV=trial-py27-twcurrent
    - python: 2.7
      env: TOXENV=trial-py27-twtrunk

    - python: 3.4
      env: TOXENV=trial-py34-tw155
    - python: 3.4
      env: TOXENV=trial-py34-tw160
    - python: 3.4
      env: TOXENV=trial-py34-twcurrent
    - python: 3.4
      env: TOXENV=trial-py34-twtrunk

    - python: 3.5
      env: TOXENV=trial-py35-tw155
    - python: 3.5
      env: TOXENV=trial-py35-tw160
    - python: 3.5
      env: TOXENV=trial-py35-twcurrent
    - python: 3.5
      env: TOXENV=trial-py35-twtrunk

    - python: 3.5
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=twistedchecker-diff
    - python: 2.7
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=docs-linkcheck

  allow_failures:
    # Tests against Twisted trunk are allow to fail, as they are not supported.
    - env: TOXENV=trial-py27-twtrunk
    - env: TOXENV=trial-py33-twtrunk
    - env: TOXENV=trial-py34-twtrunk
    - env: TOXENV=trial-py35-twtrunk
    - env: TOXENV=trial-pypy-twtrunk

    # This is not yet required.
    - env: TOXENV=twistedchecker-diff

    # This depends on external web sites, so it's allowed to fail.
    - env: TOXENV=docs-linkcheck


install:
  - ./.travis/install


script:
  - ./.travis/run tox


after_success:
  - pip install coverage codecov
  - coverage combine
  - codecov
